[package]
name = "fors-check"
version.workspace = true
license.workspace = true
edition = "2024"
publish = false

[dependencies]
fors-diag = { path = "../fors-diag" }
fors-lex = { path = "../fors-lex" }
fors-syntax = { path = "../fors-syntax" }
fors-index = { path = "../fors-index" }
fors-resolve = { path = "../fors-resolve" }
fors-fir = { path = "../fors-fir" }

[lints]
workspace = true
