[package]
name = "fors-lsp"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
fors-lex = { path = "../fors-lex" }
fors-syntax = { path = "../fors-syntax" }
fors-index = { path = "../fors-index" }
fors-resolve = { path = "../fors-resolve" }
fors-fmt = { path = "../fors-fmt" }

[lints]
workspace = true
