[package]
name = "fors-lsp"
version.workspace = true
license.workspace = true
edition = "2024"
publish = false

[dependencies]
fors-lex = { path = "../fors-lex" }
fors-syntax = { path = "../fors-syntax" }
fors-index = { path = "../fors-index" }
fors-resolve = { path = "../fors-resolve" }
fors-fmt = { path = "../fors-fmt" }
fors-diag = { path = "../fors-diag" }

[lints]
workspace = true
