[package]
name = "fors-cli"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "fors"
path = "src/main.rs"

[dependencies]
fors-lex = { path = "../fors-lex" }
fors-syntax = { path = "../fors-syntax" }
fors-index = { path = "../fors-index" }
fors-resolve = { path = "../fors-resolve" }
fors-check = { path = "../fors-check" }
fors-query = { path = "../fors-query" }

[lints]
workspace = true
