//! Increment I1's gate (design `docs/design/type-checker.md` §13):
//! `intern_is_deterministic`; `one_way_match_properties`;
//! `encode_decode_roundtrip` over 10k generated signatures; `sig_hash`
//! invariance under construction order, bound reordering and generic-parameter
//! renaming, and `sig_hash` change under a parameter rename or an
//! associated-type right-hand-side change; a birthday-bound run over 10^5
//! signatures; and one test per `decl_fingerprint` policy line (§14 Q4/Q5/Q6).
//!
//! Signatures are generated by a deterministic LCG written here — no `rand`
//! crate, and a failure is reproducible from the seed printed in the panic.

use std::collections::HashMap;

use fors_fir::constval::ConstValue;
use fors_fir::defpath::{DeclKey, DeclKeyId, ModulePathId, NO_DECL_KEY};
use fors_fir::sig::{
    Assoc, Conv, GParam, GParamKind, Member, Param, SigKind, VIS_PRIVATE, VIS_PUBLIC, NO_BOUNDS, NO_SLOT,
};
use fors_fir::subst::{one_way_match, subst_norm, Binding};
use fors_fir::ty::{PrimKind, Quals, TyId, TyTag, NO_TY, TY_ERROR, TY_NEVER, TY_UNIT};
use fors_fir::{decl_fingerprint, decode_sig, encode_sig, sig_hash, Fir, FingerprintPolicy, FINGERPRINT_POLICY};
use fors_index::decl::DeclKind;
use fors_index::ids::DefId;
use fors_index::interner::{Interner, Symbol};

// ----------------------------------------------------------------- harness

/// A deterministic 64-bit LCG (the constants are Knuth's MMIX). The high bits
/// are the ones taken: an LCG's low bits have short periods.
struct Lcg(u64);

impl Lcg {
    fn next(&mut self) -> u64 {
        self.0 = self.0.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        self.0 >> 17
    }

    fn below(&mut self, n: u64) -> u64 {
        self.next() % n
    }
}

struct W {
    fir: Fir,
    names: Interner,
    module: ModulePathId,
}

impl W {
    fn new(module: &str) -> W {
        let mut fir = Fir::new();
        let mut names = Interner::new();
        let seg = names.intern(module.as_bytes());
        let module = fir.keys.paths.intern(&[seg]);
        W { fir, names, module }
    }

    fn sym(&mut self, s: &str) -> Symbol {
        self.names.intern(s.as_bytes())
    }

    fn key(&mut self, kind: DeclKind, name: &str) -> DeclKeyId {
        let n = self.sym(name);
        self.fir.keys.intern(DeclKey { parent: NO_DECL_KEY, module: self.module, kind, name: Some(n), disamb: 0 })
    }

    fn child_key(&mut self, parent: DeclKeyId, kind: DeclKind, name: &str) -> DeclKeyId {
        let n = self.sym(name);
        self.fir.keys.intern(DeclKey { parent, module: self.module, kind, name: Some(n), disamb: 0 })
    }

    fn impl_key(&mut self, disamb: u32) -> DeclKeyId {
        self.fir.keys.intern(DeclKey { parent: NO_DECL_KEY, module: self.module, kind: DeclKind::Impl, name: None, disamb })
    }

    /// Declares a nominal head and returns its `DefId`.
    fn head(&mut self, name: &str) -> DefId {
        let k = self.key(DeclKind::Struct, name);
        self.fir.declare(k, SigKind::Struct)
    }

    fn trait_head(&mut self, name: &str) -> DefId {
        let k = self.key(DeclKind::Trait, name);
        self.fir.declare(k, SigKind::Trait)
    }

    fn trait_ref(&mut self, td: DefId, args: &[TyId]) -> fors_fir::TraitRefId {
        let a = self.fir.tys.intern_args(args);
        self.fir.tys.intern_trait_ref(td, a)
    }

    fn bounds(&mut self, trs: &[fors_fir::TraitRefId]) -> fors_fir::TraitRefListId {
        self.fir.sigs.bounds.intern(trs)
    }
}

/// The shared vocabulary a generated signature draws from.
struct Pool {
    heads: Vec<DefId>,
    traits: Vec<DefId>,
    assoc_names: Vec<Symbol>,
    prims: Vec<PrimKind>,
}

fn build_pool(w: &mut W) -> Pool {
    let heads = ["Buf", "Vec", "Map", "Pair", "Own", "Ref", "Array", "Slice", "Option", "Range"]
        .iter()
        .map(|n| w.head(n))
        .collect();
    let traits = ["Eq", "Ord", "Display", "Iterator", "Index", "Copyable"].iter().map(|n| w.trait_head(n)).collect();
    let assoc_names = ["Item", "Output", "Key"].iter().map(|n| w.sym(n)).collect();
    let prims = vec![
        PrimKind::I8,
        PrimKind::I32,
        PrimKind::I64,
        PrimKind::U8,
        PrimKind::Usize,
        PrimKind::F32,
        PrimKind::F64,
        PrimKind::Bool,
        PrimKind::Str,
        PrimKind::RawPtr,
    ];
    Pool { heads, traits, assoc_names, prims }
}

#[derive(Clone, Copy)]
struct GenCx {
    owner: DefId,
    ngp: u16,
    allow_proj: bool,
}

fn gen_ty(w: &mut W, rng: &mut Lcg, pool: &Pool, cx: GenCx, depth: u32) -> TyId {
    let leaf = depth >= 3;
    let choice = if leaf { rng.below(4) } else { rng.below(10) };
    let t = match choice {
        0 => {
            let p = pool.prims[rng.below(pool.prims.len() as u64) as usize];
            w.fir.tys.prim(p)
        }
        1 => match rng.below(3) {
            0 => TY_UNIT,
            1 => TY_NEVER,
            _ => TY_ERROR,
        },
        2 if cx.ngp > 0 => {
            let o = rng.below(cx.ngp as u64) as u16;
            w.fir.tys.param(cx.owner, o)
        }
        2 => {
            let p = pool.prims[rng.below(pool.prims.len() as u64) as usize];
            w.fir.tys.prim(p)
        }
        3 => {
            let v = ConstValue::I(rng.below(1000) as i128);
            let ty = w.fir.tys.prim(PrimKind::Usize);
            w.fir.tys.const_ty(v, ty)
        }
        4 => {
            let head = pool.heads[rng.below(pool.heads.len() as u64) as usize];
            let n = rng.below(3);
            let mut args = Vec::new();
            for _ in 0..n {
                args.push(gen_ty(w, rng, pool, cx, depth + 1));
            }
            w.fir.tys.nominal_of(head, &args)
        }
        5 => {
            let n = 1 + rng.below(3);
            let mut args = Vec::new();
            for _ in 0..n {
                args.push(gen_ty(w, rng, pool, cx, depth + 1));
            }
            w.fir.tys.tuple_of(&args)
        }
        6 => {
            let n = rng.below(3);
            let mut params = Vec::new();
            for _ in 0..n {
                let conv = match rng.below(4) {
                    0 => Conv::Let,
                    1 => Conv::Inout,
                    2 => Conv::Sink,
                    _ => Conv::Set,
                };
                params.push((conv, gen_ty(w, rng, pool, cx, depth + 1)));
            }
            let result = gen_ty(w, rng, pool, cx, depth + 1);
            let raises = if rng.below(4) == 0 { gen_ty(w, rng, pool, cx, depth + 1) } else { NO_TY };
            let closure = false; // never in a signature (§5.1)
            let f = w.fir.tys.intern_fn_ty(&params, result, raises, closure);
            w.fir.tys.fn_ty(f)
        }
        7 => {
            let td = pool.traits[rng.below(pool.traits.len() as u64) as usize];
            let n = rng.below(2);
            let mut args = Vec::new();
            for _ in 0..n {
                args.push(gen_ty(w, rng, pool, cx, depth + 1));
            }
            let tr = w.trait_ref(td, &args);
            w.fir.tys.dyn_ty(tr)
        }
        8 if cx.allow_proj && cx.ngp > 0 => {
            let o = rng.below(cx.ngp as u64) as u16;
            let head = w.fir.tys.param(cx.owner, o);
            let td = pool.traits[rng.below(pool.traits.len() as u64) as usize];
            let name = pool.assoc_names[rng.below(pool.assoc_names.len() as u64) as usize];
            let n = rng.below(2);
            let mut args = Vec::new();
            for _ in 0..n {
                args.push(gen_ty(w, rng, pool, cx, depth + 1));
            }
            let inner = w.fir.tys.proj_of(head, td, &args, name);
            // Projections on projections: R20's neutral chain.
            if rng.below(3) == 0 {
                let name2 = pool.assoc_names[rng.below(pool.assoc_names.len() as u64) as usize];
                w.fir.tys.proj_of(inner, td, &[], name2)
            } else {
                inner
            }
        }
        _ => {
            let head = pool.heads[rng.below(pool.heads.len() as u64) as usize];
            w.fir.tys.nominal_of(head, &[])
        }
    };
    // Qualifiers (`iso`/`imm` are exclusive; `secret` is orthogonal).
    match rng.below(12) {
        0 => w.fir.tys.qualified(t, Quals::ISO),
        1 => w.fir.tys.qualified(t, Quals::IMM),
        2 => w.fir.tys.qualified(t, Quals::SECRET),
        3 => {
            let q = w.fir.tys.qualified(t, Quals::IMM);
            w.fir.tys.qualified(q, Quals::SECRET)
        }
        _ => t,
    }
}

/// Generates one whole signature. `i` makes every generated signature
/// structurally distinct (a uniquely named member or a unique const value), so
/// the birthday run really does hash 10^5 *different* byte strings.
fn gen_sig(w: &mut W, rng: &mut Lcg, pool: &Pool, i: usize) -> (DeclKeyId, DefId) {
    let kinds = [SigKind::Fn, SigKind::ExternFn, SigKind::Struct, SigKind::Enum, SigKind::Trait, SigKind::Impl, SigKind::Const];
    let kind = kinds[rng.below(kinds.len() as u64) as usize];
    let decl_kind = match kind {
        SigKind::Fn => DeclKind::Fn,
        SigKind::ExternFn => DeclKind::ExternFn,
        SigKind::Struct => DeclKind::Struct,
        SigKind::Enum => DeclKind::Enum,
        SigKind::Trait => DeclKind::Trait,
        SigKind::Impl => DeclKind::Impl,
        _ => DeclKind::Const,
    };
    let key = if kind == SigKind::Impl { w.impl_key(i as u32) } else { w.key(decl_kind, &format!("d{i}")) };
    let def = w.fir.declare(key, kind);

    // Generic parameters and their bounds.
    let ngp = rng.below(4) as u16;
    let cx = GenCx { owner: def, ngp, allow_proj: true };
    let mut gparams = Vec::new();
    for g in 0..ngp {
        let name = w.sym(&format!("G{g}"));
        let gk = match rng.below(8) {
            0 => {
                let ty = w.fir.tys.prim(PrimKind::Usize);
                GParamKind::Const { ty }
            }
            1 => GParamKind::Brand,
            2 => {
                let f = w.fir.tys.intern_fn_ty(&[], TY_UNIT, NO_TY, false);
                let fn_ty = w.fir.tys.fn_ty(f);
                GParamKind::Callable { fn_ty }
            }
            _ => GParamKind::Type,
        };
        let nb = rng.below(3);
        let mut trs = Vec::new();
        for _ in 0..nb {
            let td = pool.traits[rng.below(pool.traits.len() as u64) as usize];
            let na = rng.below(2);
            let mut args = Vec::new();
            for _ in 0..na {
                args.push(gen_ty(w, rng, pool, cx, 2));
            }
            trs.push(w.trait_ref(td, &args));
        }
        let bounds = w.bounds(&trs);
        gparams.push(GParam { name, kind: gk, bounds });
    }
    // Constraint entries (R62).
    let nc = rng.below(2);
    let mut entries = Vec::new();
    for _ in 0..nc {
        let subject = gen_ty(w, rng, pool, cx, 2);
        let td = pool.traits[rng.below(pool.traits.len() as u64) as usize];
        let tr = w.trait_ref(td, &[]);
        let b = w.bounds(&[tr]);
        entries.push((subject, b));
    }
    let cl = w.fir.sigs.constraints.push(&entries);
    let g = w.fir.sigs.generics_store.push(&gparams, cl);
    w.fir.sigs.set_generics(def, g);

    let marker = w.sym(&format!("m{i}"));
    match kind {
        SigKind::Fn | SigKind::ExternFn => {
            let n = rng.below(4);
            let mut params = Vec::new();
            let marker_ty = gen_ty(w, rng, pool, cx, 1);
            params.push(Param { name: marker, conv: Conv::Let, ty: marker_ty });
            for p in 0..n {
                let name = w.sym(&format!("a{p}"));
                let conv = match rng.below(4) {
                    0 => Conv::Let,
                    1 => Conv::Inout,
                    2 => Conv::Sink,
                    _ => Conv::Set,
                };
                let ty = gen_ty(w, rng, pool, cx, 1);
                params.push(Param { name, conv, ty });
            }
            let result = gen_ty(w, rng, pool, cx, 1);
            let raises = if rng.below(3) == 0 { gen_ty(w, rng, pool, cx, 2) } else { NO_TY };
            let scoped = if rng.below(4) == 0 { 0 } else { NO_SLOT };
            let receiver = if rng.below(2) == 0 { 0 } else { NO_SLOT };
            let contract = rng.next() as u128;
            let f = w.fir.sigs.fn_sigs.push(&params, result, raises, scoped, receiver, (0, 0), contract);
            w.fir.sigs.set_fn_sig(def, f);
        }
        SigKind::Struct => {
            let n = rng.below(4);
            let mut ms = Vec::new();
            let ty = gen_ty(w, rng, pool, cx, 1);
            ms.push(Member::field(marker, VIS_PUBLIC, ty));
            for fi in 0..n {
                let name = w.sym(&format!("f{fi}"));
                let ty = gen_ty(w, rng, pool, cx, 1);
                let vis = if rng.below(2) == 0 { VIS_PUBLIC } else { VIS_PRIVATE };
                ms.push(Member::field(name, vis, ty));
            }
            let list = w.fir.sigs.member_store.push(&ms);
            w.fir.sigs.set_members(def, list);
            w.fir.sigs.set_soa(def, rng.below(4) == 0);
        }
        SigKind::Enum => {
            let n = rng.below(4);
            let mut ms = vec![Member::unit_variant(marker)];
            for vi in 0..n {
                let name = w.sym(&format!("V{vi}"));
                let m = match rng.below(3) {
                    0 => Member::unit_variant(name),
                    1 => {
                        let k = 1 + rng.below(2);
                        let mut args = Vec::new();
                        for _ in 0..k {
                            args.push(gen_ty(w, rng, pool, cx, 1));
                        }
                        let a = w.fir.tys.intern_args(&args);
                        Member::tuple_variant(name, a)
                    }
                    _ => {
                        let k = 1 + rng.below(2);
                        let mut fs = Vec::new();
                        for fi in 0..k {
                            let fname = w.sym(&format!("r{fi}"));
                            let ty = gen_ty(w, rng, pool, cx, 1);
                            fs.push(Member::field(fname, VIS_PUBLIC, ty));
                        }
                        let sub = w.fir.sigs.member_store.push(&fs);
                        Member::record_variant(name, sub)
                    }
                };
                ms.push(m);
            }
            let list = w.fir.sigs.member_store.push(&ms);
            w.fir.sigs.set_members(def, list);
        }
        SigKind::Trait => {
            let mut assocs = vec![Assoc { name: marker, bounds: NO_BOUNDS, rhs: NO_TY }];
            for ai in 0..rng.below(3) {
                let name = pool.assoc_names[ai as usize % pool.assoc_names.len()];
                let td = pool.traits[rng.below(pool.traits.len() as u64) as usize];
                let tr = w.trait_ref(td, &[]);
                let b = w.bounds(&[tr]);
                assocs.push(Assoc { name, bounds: b, rhs: NO_TY });
            }
            let a = w.fir.sigs.assocs.push(&assocs);
            w.fir.sigs.set_assoc(def, a);
            let mut items = Vec::new();
            for it in 0..rng.below(3) {
                let ik = w.child_key(key, DeclKind::Fn, &format!("t{i}_{it}"));
                let idef = w.fir.declare(ik, SigKind::Fn);
                let name = w.sym(&format!("t{i}_{it}"));
                items.push(Member::item(name, VIS_PUBLIC, idef));
            }
            let list = w.fir.sigs.member_store.push(&items);
            w.fir.sigs.set_members(def, list);
        }
        SigKind::Impl => {
            let cx2 = GenCx { allow_proj: false, ..cx };
            let self_ty = gen_ty(w, rng, pool, cx2, 1);
            w.fir.sigs.set_self_ty(def, self_ty);
            if rng.below(4) != 0 {
                let td = pool.traits[rng.below(pool.traits.len() as u64) as usize];
                let na = rng.below(2);
                let mut args = Vec::new();
                for _ in 0..na {
                    args.push(gen_ty(w, rng, pool, cx, 2));
                }
                let tr = w.trait_ref(td, &args);
                w.fir.sigs.set_trait_ref(def, tr);
            }
            let rhs = gen_ty(w, rng, pool, cx, 1);
            let mut assocs = vec![Assoc { name: marker, bounds: NO_BOUNDS, rhs }];
            for ai in 0..rng.below(2) {
                let name = pool.assoc_names[ai as usize % pool.assoc_names.len()];
                let rhs = gen_ty(w, rng, pool, cx, 1);
                assocs.push(Assoc { name, bounds: NO_BOUNDS, rhs });
            }
            let a = w.fir.sigs.assocs.push(&assocs);
            w.fir.sigs.set_assoc(def, a);
            let mut items = Vec::new();
            for it in 0..rng.below(3) {
                let ik = w.child_key(key, DeclKind::Fn, &format!("im{i}_{it}"));
                let idef = w.fir.declare(ik, SigKind::Fn);
                let name = w.sym(&format!("im{i}_{it}"));
                items.push(Member::item(name, VIS_PUBLIC, idef));
            }
            let list = w.fir.sigs.member_store.push(&items);
            w.fir.sigs.set_members(def, list);
        }
        _ => {
            // The value is under policy Q4; `i` also enters through the TYPE
            // (`Array[i64, i]`, a closed const argument, R13) so that the
            // 100k signatures stay distinct whichever way Q4 is set.
            let elem = w.fir.tys.prim(PrimKind::I64);
            let usize_ty = w.fir.tys.prim(PrimKind::Usize);
            let n = w.fir.tys.const_ty(ConstValue::I(i as i128), usize_ty);
            let ty = w.fir.tys.nominal_of(pool.heads[6], &[elem, n]);
            let v = w.fir.tys.intern_const(ConstValue::I(i as i128));
            w.fir.sigs.set_const(def, ty, v);
        }
    }
    (key, def)
}

// -------------------------------------------------------- 1. interning

#[test]
fn intern_is_deterministic() {
    // The same construction sequence in two independent stores assigns the same
    // ids, because nothing in interning consults a hash seed, an address or a
    // `HashMap` iteration order.
    let build = |seed: u64| -> (Vec<TyId>, usize) {
        let mut w = W::new("m");
        let pool = build_pool(&mut w);
        let mut rng = Lcg(seed);
        let owner = w.head("Owner");
        let cx = GenCx { owner, ngp: 3, allow_proj: true };
        let ts: Vec<TyId> = (0..2000).map(|_| gen_ty(&mut w, &mut rng, &pool, cx, 0)).collect();
        (ts, w.fir.tys.len())
    };
    let (a, la) = build(12345);
    let (b, lb) = build(12345);
    assert_eq!(a, b);
    assert_eq!(la, lb);

    // And re-building an identical type interns nothing new (R9: equality is
    // the id).
    let mut w = W::new("m");
    let pool = build_pool(&mut w);
    let owner = w.head("Owner");
    let cx = GenCx { owner, ngp: 2, allow_proj: true };
    let mut rng = Lcg(7);
    let t = gen_ty(&mut w, &mut rng, &pool, cx, 0);
    let before = w.fir.tys.len();
    let mut rng2 = Lcg(7);
    let t2 = gen_ty(&mut w, &mut rng2, &pool, cx, 0);
    assert_eq!(t, t2);
    assert_eq!(w.fir.tys.len(), before, "re-interning an existing type grew the store");
}

// ------------------------------------------------- 2. the one-way match

#[test]
fn one_way_match_properties() {
    let mut w = W::new("m");
    let pool = build_pool(&mut w);
    let owner = w.head("Callee");
    let mut rng = Lcg(0xFEED);

    // (a) Reflexivity on ground types, binding nothing.
    let ground = GenCx { owner, ngp: 0, allow_proj: false };
    for _ in 0..500 {
        let t = gen_ty(&mut w, &mut rng, &pool, ground, 0);
        let mut b = Binding::new(&[(owner, 3)]);
        assert!(one_way_match(&mut w.fir.tys, t, t, &mut b), "a type failed to match itself");
        assert!(b.slots().iter().all(|&s| s == NO_TY), "matching a ground type bound a slot");
    }

    // (b) Soundness: a complete match means substitution reproduces the target
    // exactly. Patterns here are projection-free, since a projection on an
    // unbound parameter is deliberately skipped rather than matched (R38(e)).
    let open = GenCx { owner, ngp: 3, allow_proj: false };
    let mut checked = 0;
    for _ in 0..3000 {
        let pattern = gen_ty(&mut w, &mut rng, &pool, open, 0);
        let mut src = Binding::new(&[(owner, 3)]);
        for o in 0..3u16 {
            let t = gen_ty(&mut w, &mut rng, &pool, ground, 1);
            assert!(src.bind(owner, o, t));
        }
        let Some(target) = subst_norm(&mut w.fir.tys, pattern, &src) else { continue };
        let mut b = Binding::new(&[(owner, 3)]);
        assert!(one_way_match(&mut w.fir.tys, pattern, target, &mut b), "a substituted instance did not match");
        assert_eq!(
            subst_norm(&mut w.fir.tys, pattern, &b),
            Some(target),
            "match succeeded but substituting the binding did not reproduce the target"
        );
        checked += 1;
    }
    assert!(checked > 100, "the soundness sweep never got off the ground ({checked} cases)");

    // (c) One-way: nothing in the target is ever bound. A ground pattern facing
    // a parameter-bearing target matches only if they are literally equal.
    for _ in 0..500 {
        let p = gen_ty(&mut w, &mut rng, &pool, ground, 0);
        let a = gen_ty(&mut w, &mut rng, &pool, open, 0);
        let mut b = Binding::new(&[(owner, 3)]);
        let ok = one_way_match(&mut w.fir.tys, p, a, &mut b);
        if ok {
            assert_eq!(p, a, "a ground pattern matched a different target");
        }
        assert!(b.slots().iter().all(|&s| s == NO_TY));
    }

    // (d) Different heads never match.
    let v = w.fir.tys.prim(PrimKind::I32);
    let u = w.fir.tys.prim(PrimKind::U8);
    let ta = w.fir.tys.tuple_of(&[v, u]);
    let tb = w.fir.tys.tuple_of(&[v, u, v]);
    let mut b = Binding::new(&[(owner, 1)]);
    assert!(!one_way_match(&mut w.fir.tys, ta, tb, &mut b));
    assert!(!one_way_match(&mut w.fir.tys, ta, TY_UNIT, &mut b));
    assert!(!one_way_match(&mut w.fir.tys, TY_NEVER, TY_UNIT, &mut b));

    // (e) A parameter of a declaration the binding does not own is rigid.
    let other = w.head("Other");
    let foreign = w.fir.tys.param(other, 0);
    let mut b = Binding::new(&[(owner, 1)]);
    assert!(one_way_match(&mut w.fir.tys, foreign, foreign, &mut b));
    assert!(!one_way_match(&mut w.fir.tys, foreign, v, &mut b));
}

// ------------------------------------------------- 3. encode / decode

fn rebuild_key(dst: &mut W, src: &W, key: DeclKeyId) -> DeclKeyId {
    let row = src.fir.keys.row(key);
    let parent = if row.parent == NO_DECL_KEY { NO_DECL_KEY } else { rebuild_key(dst, src, row.parent) };
    let segs: Vec<Symbol> = src
        .fir
        .keys
        .paths
        .segments(row.module)
        .iter()
        .map(|&s| {
            let bytes = src.names.resolve(s).to_vec();
            dst.names.intern(&bytes)
        })
        .collect();
    let module = dst.fir.keys.paths.intern(&segs);
    let name = row.name.map(|n| {
        let bytes = src.names.resolve(n).to_vec();
        dst.names.intern(&bytes)
    });
    dst.fir.keys.intern(DeclKey { parent, module, kind: row.kind, name, disamb: row.disamb })
}

#[test]
fn encode_decode_roundtrip() {
    const N: usize = 10_000;
    let policy = FINGERPRINT_POLICY;
    let mut w = W::new("m");
    let pool = build_pool(&mut w);
    let mut rng = Lcg(0xC0FFEE);
    let mut dst = W::new("m");

    for i in 0..N {
        let (key, def) = gen_sig(&mut w, &mut rng, &pool, i);
        let bytes = encode_sig(&w.fir, &w.names, def, policy);
        let hash = sig_hash(&w.fir, &w.names, def);

        let dst_key = rebuild_key(&mut dst, &w, key);
        let dst_def = match decode_sig(&bytes, &mut dst.fir, &mut dst.names, dst_key) {
            Ok(d) => d,
            Err(e) => panic!("signature {i} failed to decode: {e:?}"),
        };
        let again = encode_sig(&dst.fir, &dst.names, dst_def, policy);
        assert!(
            bytes == again,
            "signature {i} ({:?}) did not re-encode identically:\n  {} bytes out, {} bytes back",
            w.fir.sigs.kind(def),
            bytes.len(),
            again.len()
        );
        assert_eq!(sig_hash(&dst.fir, &dst.names, dst_def), hash, "signature {i}: hash changed across a round trip");
    }
}

// ------------------------------------------------- 4. hash invariants

/// Builds `fn f[T: Eq + Ord](let x: Pair[T, i32]) -> T` with the bound list and
/// the generic-parameter name as parameters of the construction, so the three
/// invariance cases differ in exactly one thing each.
fn build_fn(
    module: &str,
    gparam_name: &str,
    param_name: &str,
    bounds_reversed: bool,
    extra_types_first: bool,
) -> (W, DefId) {
    let mut w = W::new(module);
    if extra_types_first {
        // Intern unrelated types first so every id in the signature differs.
        let junk = w.head("Junk");
        for k in 0..7 {
            let p = w.fir.tys.prim(PrimKind::from_u8(k).unwrap());
            let _ = w.fir.tys.nominal_of(junk, &[p]);
        }
    }
    let eq = w.trait_head("Eq");
    let ord = w.trait_head("Ord");
    let pair = w.head("Pair");
    let key = w.key(DeclKind::Fn, "f");
    let def = w.fir.declare(key, SigKind::Fn);

    let eq_ref = w.trait_ref(eq, &[]);
    let ord_ref = w.trait_ref(ord, &[]);
    let list = if bounds_reversed { vec![ord_ref, eq_ref] } else { vec![eq_ref, ord_ref] };
    // The store sorts, so the *encoder* is what this case really exercises:
    // build the list in both orders through the raw pools.
    let bounds = w.bounds(&list);
    let gname = w.sym(gparam_name);
    let g = w.fir.sigs.generics_store.push(
        &[GParam { name: gname, kind: GParamKind::Type, bounds }],
        fors_fir::NO_CONSTRAINTS,
    );
    w.fir.sigs.set_generics(def, g);

    let t = w.fir.tys.param(def, 0);
    let i32_ty = w.fir.tys.prim(PrimKind::I32);
    let pair_ty = w.fir.tys.nominal_of(pair, &[t, i32_ty]);
    let pname = w.sym(param_name);
    let f = w
        .fir
        .sigs
        .fn_sigs
        .push(&[Param { name: pname, conv: Conv::Let, ty: pair_ty }], t, NO_TY, NO_SLOT, NO_SLOT, (0, 0), 0);
    w.fir.sigs.set_fn_sig(def, f);
    (w, def)
}

#[test]
fn sig_hash_is_invariant_under_construction_order() {
    // The FIR has no formatting, so "reformatting does not change the hash" is,
    // at this layer, "the order types happened to be interned in does not
    // change the hash" — which is the stronger statement, and the one that
    // makes the hash comparable between two builds at all.
    let (a, da) = build_fn("m", "T", "x", false, false);
    let (b, db) = build_fn("m", "T", "x", false, true);
    assert_ne!(
        a.fir.tys.len(),
        b.fir.tys.len(),
        "the two builds were meant to differ in how many types they interned"
    );
    assert_eq!(sig_hash(&a.fir, &a.names, da), sig_hash(&b.fir, &b.names, db));
}

#[test]
fn bound_order_does_not_change_the_fingerprint() {
    // §14 Q6. Flip `sort_bound_lists` and this is the test that changes.
    //
    // MARC (verification round): the same-store form below is vacuous on its
    // own — `TraitRefLists::intern` already sorts by `TraitRefId`, so within
    // ONE store both orders are one list and the encoder's sort is never
    // exercised. The form that detects the flip is two stores whose trait
    // refs were interned in opposite orders: their store-level lists disagree,
    // and only the encoder's sort by canonical bytes makes the hashes agree.
    let mut fwd = W::new("m");
    let mut rev = W::new("m");
    let x = raw_bounds_sig(&mut fwd, false);
    let y = raw_bounds_sig(&mut rev, true);
    assert_eq!(
        decl_fingerprint(&fwd.fir, &fwd.names, x),
        decl_fingerprint(&rev.fir, &rev.names, y),
        "a bound list interned in the other order changed the fingerprint"
    );
    let (a, da) = build_fn("m", "T", "x", false, false);
    let (b, db) = build_fn("m", "T", "x", true, false);
    assert_eq!(decl_fingerprint(&a.fir, &a.names, da), decl_fingerprint(&b.fir, &b.names, db));

    // The unsorted policy is what makes the two differ, which is what the line
    // in `FINGERPRINT_POLICY` selects between.
    let unsorted = FingerprintPolicy { sort_bound_lists: false, ..FINGERPRINT_POLICY };
    assert_ne!(
        encode_sig(&fwd.fir, &fwd.names, x, unsorted),
        encode_sig(&rev.fir, &rev.names, y, unsorted),
        "with sorting off the two orders must be distinguishable, or the test proves nothing"
    );
}

/// `fn f[T: A + B]` with the bound list interned in the given order, bypassing
/// `TraitRefLists`' own sort so the encoder is the only thing that can
/// canonicalise it.
fn raw_bounds_sig(w: &mut W, reversed: bool) -> DefId {
    // Interning the traits in the opposite order makes their `TraitRefId`s sort
    // the other way, which is how a store-level list ends up "reversed".
    let (first, second) = if reversed { ("B", "A") } else { ("A", "B") };
    let t1 = w.trait_head(first);
    let t2 = w.trait_head(second);
    let r1 = w.trait_ref(t1, &[]);
    let r2 = w.trait_ref(t2, &[]);
    let bounds = w.bounds(&[r1, r2]);
    let key = w.key(DeclKind::Fn, "f");
    let def = w.fir.declare(key, SigKind::Fn);
    let gname = w.sym("T");
    let g = w
        .fir
        .sigs
        .generics_store
        .push(&[GParam { name: gname, kind: GParamKind::Type, bounds }], fors_fir::NO_CONSTRAINTS);
    w.fir.sigs.set_generics(def, g);
    let f = w.fir.sigs.fn_sigs.push(&[], TY_UNIT, NO_TY, NO_SLOT, NO_SLOT, (0, 0), 0);
    w.fir.sigs.set_fn_sig(def, f);
    def
}

#[test]
fn gparam_names_do_not_enter_the_fingerprint() {
    // §14 Q5. Flip `exclude_gparam_names` and this is the test that changes.
    let (a, da) = build_fn("m", "T", "x", false, false);
    let (b, db) = build_fn("m", "U", "x", false, false);
    assert_eq!(decl_fingerprint(&a.fir, &a.names, da), decl_fingerprint(&b.fir, &b.names, db));
}

#[test]
fn a_value_parameter_rename_changes_the_hash() {
    // R37 makes a label observable, so this one MUST move.
    let (a, da) = build_fn("m", "T", "x", false, false);
    let (b, db) = build_fn("m", "T", "y", false, false);
    assert_ne!(sig_hash(&a.fir, &a.names, da), sig_hash(&b.fir, &b.names, db));
}

#[test]
fn an_associated_type_right_hand_side_change_changes_the_hash() {
    // R2: an impl's `type A = T;` is part of its signature.
    let build = |rhs_is_i32: bool| -> (W, DefId) {
        let mut w = W::new("m");
        let it = w.trait_head("Iterator");
        let vec = w.head("Vec");
        let key = w.impl_key(0);
        let def = w.fir.declare(key, SigKind::Impl);
        let i32_ty = w.fir.tys.prim(PrimKind::I32);
        let u8_ty = w.fir.tys.prim(PrimKind::U8);
        let self_ty = w.fir.tys.nominal_of(vec, &[i32_ty]);
        w.fir.sigs.set_self_ty(def, self_ty);
        let tr = w.trait_ref(it, &[]);
        w.fir.sigs.set_trait_ref(def, tr);
        let item = w.sym("Item");
        let rhs = if rhs_is_i32 { i32_ty } else { u8_ty };
        let a = w.fir.sigs.assocs.push(&[Assoc { name: item, bounds: NO_BOUNDS, rhs }]);
        w.fir.sigs.set_assoc(def, a);
        (w, def)
    };
    let (a, da) = build(true);
    let (b, db) = build(false);
    assert_ne!(sig_hash(&a.fir, &a.names, da), sig_hash(&b.fir, &b.names, db));
}

#[test]
fn const_value_enters_the_fingerprint() {
    // §14 Q4. Flip `include_const_value` and this is the test that changes.
    let build = |v: i128| -> (W, DefId) {
        let mut w = W::new("m");
        let key = w.key(DeclKind::Const, "LIMIT");
        let def = w.fir.declare(key, SigKind::Const);
        let ty = w.fir.tys.prim(PrimKind::I64);
        let val = w.fir.tys.intern_const(ConstValue::I(v));
        w.fir.sigs.set_const(def, ty, val);
        (w, def)
    };
    let (a, da) = build(16);
    let (b, db) = build(32);
    assert_ne!(
        decl_fingerprint(&a.fir, &a.names, da),
        decl_fingerprint(&b.fir, &b.names, db),
        "the comptime value of a const declaration must be in its fingerprint"
    );

    // And the other policy really is distinguishable, so the line matters.
    let excluded = FingerprintPolicy { include_const_value: false, exclude_gparam_names: true, sort_bound_lists: true };
    assert_eq!(encode_sig(&a.fir, &a.names, da, excluded), encode_sig(&b.fir, &b.names, db, excluded));
}

// ------------------------------------------------- 5. birthday bound

#[test]
fn sig_hash_has_no_collision_over_100k_signatures() {
    const N: usize = 100_000;
    let mut w = W::new("m");
    let pool = build_pool(&mut w);
    let mut rng = Lcg(0xB17D_A1);
    let policy = FINGERPRINT_POLICY;
    let mut seen: HashMap<u128, Vec<u8>> = HashMap::with_capacity(N);
    let mut distinct = 0usize;
    for i in 0..N {
        let (_, def) = gen_sig(&mut w, &mut rng, &pool, i);
        let bytes = encode_sig(&w.fir, &w.names, def, policy);
        let h = decl_fingerprint(&w.fir, &w.names, def);
        match seen.get(&h) {
            None => {
                distinct += 1;
                seen.insert(h, bytes);
            }
            Some(prev) => assert!(
                *prev == bytes,
                "128-bit collision at signature {i}: two different encodings hash to {h:#034x}"
            ),
        }
    }
    assert!(distinct >= 100_000, "only {distinct} distinct signatures were generated");
}

// ------------------------------------------------- misc invariants

#[test]
fn the_store_rejects_a_projection_on_a_concrete_head() {
    // The §5.1 invariant, in the form the checker relies on: `Proj`'s head is
    // `Param` or `Proj`, so `is_rigid` on a head is a tag test and normalisation
    // never has to ask whether a projection "should" have been reduced.
    let mut w = W::new("m");
    let owner = w.head("Owner");
    let p = w.fir.tys.param(owner, 0);
    let item = w.sym("Item");
    let tr = w.trait_head("Iterator");
    let proj = w.fir.tys.proj_of(p, tr, &[], item);
    assert_eq!(w.fir.tys.tag(proj), TyTag::Proj);
    assert!(w.fir.tys.is_rigid(proj));
    let deeper = w.fir.tys.proj_of(proj, tr, &[], item);
    assert!(w.fir.tys.is_rigid(deeper));
    assert!(!w.fir.tys.is_monomorphic(deeper));
}

// ------------------------------------------- 5. verifier properties
//
// MARC (verification round, 2026-09-20): the tests above check the I1 gate as
// written. The ones below check the claims BEHIND the gate by property —
// interning IS structural equality, substitution composes, the match never
// revises, the encoding does not depend on pool warmth, and the decoder cannot
// be made to panic by bytes it did not write.

/// Structural equality on two rows of two (possibly different) stores, written
/// independently of the interner: the paranoid comparison `TyId == TyId` is
/// supposed to be equivalent to.
fn struct_eq(sa: &fors_fir::TyStore, a: TyId, sb: &fors_fir::TyStore, b: TyId) -> bool {
    if sa.tag(a) != sb.tag(b) || sa.quals(a) != sb.quals(b) {
        return false;
    }
    let args_eq = |xa: fors_fir::ArgsId, xb: fors_fir::ArgsId| -> bool {
        let (la, lb) = (sa.args(xa), sb.args(xb));
        la.len() == lb.len() && la.iter().zip(lb).all(|(&x, &y)| struct_eq(sa, x, sb, y))
    };
    let tr_eq = |ta: fors_fir::TraitRefId, tb: fors_fir::TraitRefId| -> bool {
        let ((da, xa), (db, xb)) = (sa.trait_ref(ta), sb.trait_ref(tb));
        da == db && args_eq(xa, xb)
    };
    match sa.tag(a) {
        TyTag::Error | TyTag::Unit | TyTag::Never => true,
        TyTag::Prim | TyTag::Param => sa.a(a) == sb.a(b) && sa.b(a) == sb.b(b),
        TyTag::Nominal => sa.a(a) == sb.a(b) && args_eq(fors_fir::ArgsId(sa.b(a)), fors_fir::ArgsId(sb.b(b))),
        TyTag::Tuple => args_eq(fors_fir::ArgsId(sa.b(a)), fors_fir::ArgsId(sb.b(b))),
        TyTag::Dyn => tr_eq(fors_fir::TraitRefId(sa.a(a)), fors_fir::TraitRefId(sb.a(b))),
        TyTag::Fn => {
            let (fa, fb) = (fors_fir::FnTyId(sa.a(a)), fors_fir::FnTyId(sb.a(b)));
            let ((ca, ta), (cb, tb)) = (sa.fn_tys().params(fa), sb.fn_tys().params(fb));
            let raises = match (sa.fn_tys().raises(fa), sb.fn_tys().raises(fb)) {
                (NO_TY, NO_TY) => true,
                (NO_TY, _) | (_, NO_TY) => false,
                (x, y) => struct_eq(sa, x, sb, y),
            };
            ca == cb
                && ta.len() == tb.len()
                && ta.iter().zip(tb).all(|(&x, &y)| struct_eq(sa, x, sb, y))
                && struct_eq(sa, sa.fn_tys().result(fa), sb, sb.fn_tys().result(fb))
                && raises
                && sa.fn_tys().is_closure(fa) == sb.fn_tys().is_closure(fb)
        }
        TyTag::Proj => {
            let ((ta, na), (tb, nb)) =
                (sa.proj_key(fors_fir::ProjKeyId(sa.b(a))), sb.proj_key(fors_fir::ProjKeyId(sb.b(b))));
            na == nb && tr_eq(ta, tb) && struct_eq(sa, TyId(sa.a(a)), sb, TyId(sb.a(b)))
        }
        TyTag::Brand => sa.brand(fors_fir::BrandId(sa.b(a))) == sb.brand(fors_fir::BrandId(sb.b(b))),
        TyTag::ConstVal => {
            sa.const_value(fors_fir::ConstId(sa.a(a))) == sb.const_value(fors_fir::ConstId(sb.a(b)))
                && struct_eq(sa, TyId(sa.b(a)), sb, TyId(sb.b(b)))
        }
    }
}

#[test]
fn interning_is_exactly_structural_equality() {
    let mut w = W::new("m");
    let pool = build_pool(&mut w);
    let owner = w.head("Owner");
    let cx = GenCx { owner, ngp: 3, allow_proj: true };
    let mut rng = Lcg(0xA11CE);
    let ts: Vec<TyId> = (0..700).map(|_| gen_ty(&mut w, &mut rng, &pool, cx, 0)).collect();
    let mut equal_pairs = 0u32;
    for i in 0..ts.len() {
        for j in 0..ts.len() {
            let by_id = ts[i] == ts[j];
            let by_shape = struct_eq(&w.fir.tys, ts[i], &w.fir.tys, ts[j]);
            assert_eq!(by_id, by_shape, "ids {:?} / {:?}: id-equality and structural equality disagree", ts[i], ts[j]);
            if by_id && i != j {
                equal_pairs += 1;
            }
        }
    }
    assert!(equal_pairs > 50, "the sweep produced too few duplicate types ({equal_pairs}) to mean anything");

    // Across two stores warmed differently the ids differ but shapes agree:
    // the same generator sequence yields structurally equal rows at each step.
    let mut w2 = W::new("m");
    let pool2 = build_pool(&mut w2);
    let owner2 = w2.head("Owner");
    let cx2 = GenCx { owner: owner2, ngp: 3, allow_proj: true };
    let mut junk = Lcg(99);
    for _ in 0..1500 {
        let _ = gen_ty(&mut w2, &mut junk, &pool2, cx2, 0);
    }
    let mut rng2 = Lcg(0xA11CE);
    let ts2: Vec<TyId> = (0..700).map(|_| gen_ty(&mut w2, &mut rng2, &pool2, cx2, 0)).collect();
    assert_ne!(ts, ts2, "the warm store was meant to assign different ids");
    for i in 0..ts.len() {
        assert!(struct_eq(&w.fir.tys, ts[i], &w2.fir.tys, ts2[i]), "step {i}: the warm store built a different shape");
    }
}

#[test]
fn substitution_composes_and_is_idempotent() {
    // p over A; b1: A := types over B; b2: B := ground. Then
    // subst(subst(p, b1), b2) == subst(p, b1 ∘ b2), and the result is a fixed
    // point of every further substitution.
    let mut w = W::new("m");
    let pool = build_pool(&mut w);
    let a = w.head("A");
    let bdef = w.head("B");
    let mut rng = Lcg(0xC0DE);
    let over_a = GenCx { owner: a, ngp: 3, allow_proj: true };
    let over_b = GenCx { owner: bdef, ngp: 2, allow_proj: true };
    let ground = GenCx { owner: bdef, ngp: 0, allow_proj: false };
    let (mut composed, mut identity) = (0, 0);
    for _ in 0..3000 {
        let p = gen_ty(&mut w, &mut rng, &pool, over_a, 0);
        let mut b1 = Binding::new(&[(a, 3)]);
        for o in 0..3 {
            let t = gen_ty(&mut w, &mut rng, &pool, over_b, 1);
            assert!(b1.bind(a, o, t));
        }
        let mut b2 = Binding::new(&[(bdef, 2)]);
        for o in 0..2 {
            let t = gen_ty(&mut w, &mut rng, &pool, ground, 1);
            assert!(b2.bind(bdef, o, t));
        }
        // b1 ∘ b2 as one binding of A.
        let mut b12 = Binding::new(&[(a, 3)]);
        let mut all = true;
        for o in 0..3u16 {
            match subst_norm(&mut w.fir.tys, b1.slot(a, o), &b2) {
                Some(t) => assert!(b12.bind(a, o, t)),
                None => all = false,
            }
        }
        if !all {
            continue;
        }
        let stepwise = subst_norm(&mut w.fir.tys, p, &b1).and_then(|q| subst_norm(&mut w.fir.tys, q, &b2));
        let direct = subst_norm(&mut w.fir.tys, p, &b12);
        assert_eq!(stepwise, direct, "substitution did not compose on {p:?}");
        if let Some(r) = direct {
            composed += 1;
            let before = w.fir.tys.len();
            assert_eq!(subst_norm(&mut w.fir.tys, r, &b12), Some(r), "not idempotent");
            assert_eq!(subst_norm(&mut w.fir.tys, r, &b1), Some(r), "a ground result changed under a second substitution");
            assert_eq!(w.fir.tys.len(), before, "re-substituting a fixed point interned something");
        }
        // A type with no parameter of A is untouched by a binding of A.
        let free = gen_ty(&mut w, &mut rng, &pool, over_b, 0);
        let before = w.fir.tys.len();
        assert_eq!(subst_norm(&mut w.fir.tys, free, &b1), Some(free));
        assert_eq!(w.fir.tys.len(), before);
        identity += 1;
    }
    assert!(composed > 300, "too few composed cases ({composed})");
    assert!(identity > 1000);
}

#[test]
fn one_way_match_never_revises_and_never_binds_the_target() {
    let mut w = W::new("m");
    let pool = build_pool(&mut w);
    let a = w.head("A");
    let bdef = w.head("B");
    let mut rng = Lcg(0xB1AD);
    let over_a = GenCx { owner: a, ngp: 3, allow_proj: false };
    let over_b = GenCx { owner: bdef, ngp: 2, allow_proj: true };
    let mut revisits = 0;
    for _ in 0..3000 {
        let p = gen_ty(&mut w, &mut rng, &pool, over_a, 0);
        let mut src = Binding::new(&[(a, 3)]);
        for o in 0..3 {
            let t = gen_ty(&mut w, &mut rng, &pool, over_b, 1);
            assert!(src.bind(a, o, t));
        }
        let Some(target) = subst_norm(&mut w.fir.tys, p, &src) else { continue };
        // The target mentions B's parameters; the binding owns only A, so the
        // only way to "bind" B would be to write into a slot that is not
        // there — `Binding::bind` refuses, and the slots stay A's.
        let mut b = Binding::new(&[(a, 3)]);
        assert!(one_way_match(&mut w.fir.tys, p, target, &mut b));
        let snapshot = b.slots().to_vec();
        for &s in &snapshot {
            if s != NO_TY {
                // Every bound value is a subterm of the target, never a
                // parameter of A (nothing on the pattern side leaks in).
                assert!(w.fir.tys.tag(s) != TyTag::Param || DefId(w.fir.tys.a(s)) != a);
            }
        }
        // Matching again is a no-op: same answer, same slots.
        assert!(one_way_match(&mut w.fir.tys, p, target, &mut b));
        assert_eq!(b.slots(), snapshot.as_slice(), "a second identical match revised a slot");
        // A different instance of the same pattern cannot re-bind a bound slot.
        let mut src2 = Binding::new(&[(a, 3)]);
        for o in 0..3 {
            let t = gen_ty(&mut w, &mut rng, &pool, over_b, 1);
            assert!(src2.bind(a, o, t));
        }
        if let Some(target2) = subst_norm(&mut w.fir.tys, p, &src2) {
            if target2 != target {
                // The instances differ, so some slot the pattern mentions must
                // disagree: the match fails, and every slot that was bound
                // before is exactly what it was (a failed match may bind a
                // slot that was free — that is R38's "bound by an earlier
                // argument" — but it never rewrites one).
                let ok = one_way_match(&mut w.fir.tys, p, target2, &mut b);
                assert!(!ok, "a binding accepted a second, different instance of its pattern");
                for (i, &s) in snapshot.iter().enumerate() {
                    if s != NO_TY {
                        assert_eq!(b.slots()[i], s, "a failed match revised slot {i}");
                    }
                }
                revisits += 1;
            }
        }
    }
    assert!(revisits > 100, "too few revision attempts ({revisits})");
}

#[test]
fn encoding_is_independent_of_pool_warmth_and_interner_order() {
    // The same 300 signatures, generated from the same seed, in a fresh
    // world and in one whose pools and interner were warmed with unrelated
    // rows first (so every id and every Symbol differs): byte-identical.
    // Run twice in one process with two different warmings.
    let policy = FINGERPRINT_POLICY;
    let cold = {
        let mut w = W::new("m");
        let pool = build_pool(&mut w);
        let mut rng = Lcg(0x5EED);
        (0..300)
            .map(|i| {
                let (_, def) = gen_sig(&mut w, &mut rng, &pool, i);
                (encode_sig(&w.fir, &w.names, def, policy), sig_hash(&w.fir, &w.names, def))
            })
            .collect::<Vec<_>>()
    };
    for (round, warm_types, warm_names) in [(1u64, 2000usize, 300usize), (2, 137, 4000)] {
        let mut w = W::new("m");
        for k in 0..warm_names {
            let _ = w.sym(&format!("junk{k}"));
        }
        let junk_owner = w.head("JunkOwner");
        let pool = build_pool(&mut w);
        let mut junk = Lcg(round);
        for _ in 0..warm_types {
            let _ = gen_ty(&mut w, &mut junk, &pool, GenCx { owner: junk_owner, ngp: 2, allow_proj: true }, 0);
        }
        let mut rng = Lcg(0x5EED);
        for i in 0..300 {
            let (_, def) = gen_sig(&mut w, &mut rng, &pool, i);
            let bytes = encode_sig(&w.fir, &w.names, def, policy);
            assert!(bytes == cold[i].0, "round {round}, signature {i}: the encoding depends on pool warmth");
            assert_eq!(sig_hash(&w.fir, &w.names, def), cold[i].1, "round {round}, signature {i}: hash moved");
        }
    }
}

#[test]
fn decode_never_panics_on_malformed_bytes() {
    use fors_fir::DecodeError;
    let policy = FINGERPRINT_POLICY;
    let mut w = W::new("m");
    let pool = build_pool(&mut w);
    let mut rng = Lcg(0xBAD);
    let mut dst = W::new("m");
    let anchor = dst.key(DeclKind::Fn, "anchor");
    let (mut oks, mut errs) = (0u32, 0u32);
    // 500 x 4 = 2000 decodes: ~3 s in a debug build, which is what CI runs.
    for i in 0..500 {
        let (_, def) = gen_sig(&mut w, &mut rng, &pool, i);
        let bytes = encode_sig(&w.fir, &w.names, def, policy);
        for _ in 0..4 {
            let mut m = bytes.clone();
            let at = rng.below(m.len() as u64) as usize;
            match rng.below(5) {
                0 => m[at] ^= 1 << rng.below(8),
                1 => m.truncate(at),
                2 => m.insert(at, rng.next() as u8),
                3 => m[at] = 0xFF,
                _ => m[at] = 0x01,
            }
            match decode_sig(&m, &mut dst.fir, &mut dst.names, anchor) {
                Ok(_) => oks += 1,
                Err(_) => errs += 1,
            }
        }
    }
    assert!(errs > 500 && oks > 0, "mutation sweep: {oks} ok / {errs} err");

    // Crafted bombs: each was a panic or an abort before the count guards.
    let head = |n_entries: &[u8]| -> Vec<u8> {
        let mut v = b"FIR1".to_vec();
        v.push(7);
        v.extend_from_slice(n_entries);
        v
    };
    // 2^62 entries: capacity overflow.
    let mut v = head(&[0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x40]);
    v.extend_from_slice(&[0; 32]);
    assert!(matches!(decode_sig(&v, &mut dst.fir, &mut dst.names, anchor), Err(DecodeError::BadCount(_))));
    // A function type with 300 parameters: `expect("more than 255 parameters")`.
    let mut v = head(&[1]);
    v.extend_from_slice(&[7, 0, 0, 0xAC, 0x02]);
    v.extend_from_slice(&[0; 900]);
    assert!(matches!(decode_sig(&v, &mut dst.fir, &mut dst.names, anchor), Err(DecodeError::BadCount(300))));
    // An empty tuple: a store-invariant violation.
    let mut v = head(&[1]);
    v.extend_from_slice(&[6, 0, 0]);
    assert!(matches!(decode_sig(&v, &mut dst.fir, &mut dst.names, anchor), Err(DecodeError::BadShape)));
    // A projection on a concrete head.
    let mut v = head(&[2]);
    v.extend_from_slice(&[4, 0, 1]); // a primitive
    v.extend_from_slice(&[10, 0, 0]); // proj, quals 0, head = entry 0
    v.extend_from_slice(&[0; 16]);
    assert!(matches!(decode_sig(&v, &mut dst.fir, &mut dst.names, anchor), Err(DecodeError::BadShape)));
    // `iso imm` and an unknown qualifier bit.
    for q in [3u8, 0x80] {
        let mut v = head(&[1]);
        v.extend_from_slice(&[2, q]);
        assert!(matches!(decode_sig(&v, &mut dst.fir, &mut dst.names, anchor), Err(DecodeError::BadShape)));
    }
    // A declaration key nested 100 000 deep: a stack overflow before.
    let mut v = head(&[1]);
    v.extend_from_slice(&[5, 0]);
    v.extend_from_slice(&[1u8; 100_000]);
    assert!(matches!(decode_sig(&v, &mut dst.fir, &mut dst.names, anchor), Err(DecodeError::TooDeep)));
    // The encoder's "no DeclKey" marker (mark 2) on a nominal head: this was
    // `def_for_key(NO_DECL_KEY)`, a 16 GB table resize, 2.7 s per byte flip.
    let mut v = head(&[1]);
    v.extend_from_slice(&[5, 0, 2]);
    v.extend_from_slice(&[0; 8]);
    let t = std::time::Instant::now();
    assert!(matches!(decode_sig(&v, &mut dst.fir, &mut dst.names, anchor), Err(DecodeError::BadShape)));
    assert!(t.elapsed().as_millis() < 500, "the no-key marker took {:?} to reject", t.elapsed());
}
