[package]
name = "fors-fmt"
version.workspace = true
edition = "2024"
publish = false

[dependencies]
fors-lex = { path = "../fors-lex" }
fors-syntax = { path = "../fors-syntax" }

[dev-dependencies]
fors-lex = { path = "../fors-lex" }
fors-index = { path = "../fors-index" }
fors-resolve = { path = "../fors-resolve" }

[lints]
workspace = true
